[package]
name = "trace0"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
trace0-core.workspace = true
trace0-json.workspace = true
trace0-proto.workspace = true
ahash.workspace = true
clap.workspace = true
parking_lot.workspace = true
pyo3.workspace = true

[workspace]
members = ["crates/core", "crates/json", "crates/proto"]

[workspace.package]
version = "0.1.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/soof-golan/trace0"

[workspace.dependencies]
trace0-core = { path = "crates/core" }
trace0-json = { path = "crates/json" }
trace0-proto = { path = "crates/proto" }
ahash = "0.8.12"
clap = { version = "4.6.1", features = ["derive"] }
libc = "0.2.186"
parking_lot = "0.12.5"
prost = "0.14.3"
prost-build = "0.14.3"
protox = "0.9.1"
pyo3 = { version = "0.28.3", features = ["extension-module"] }
rtrb = "0.3.4"
serde_json = "1.0.149"
