[workspace]
resolver = "3"
members = ["crates/core", "crates/json", "crates/proto", "crates/py"]

[workspace.package]
version = "0.1.5"
edition = "2024"
license = "MIT"
repository = "https://github.com/soof-golan/trace0"

[workspace.dependencies]
trace0-core = { path = "crates/core" }
trace0-json = { path = "crates/json" }
trace0-proto = { path = "crates/proto" }
ahash = "0.8.12"
quanta = "0.12.6"
clap = { version = "4.6.1", features = ["derive"] }
libc = "0.2.186"
parking_lot = "0.12.5"
prost = "0.14.3"
prost-build = "0.14.3"
protox = "0.9.1"
pyo3 = { version = "0.28.3", features = ["extension-module"] }
rtrb = "0.3.4"
serde_json = "1.0.149"
